export const Data = {
  data: [
    {
      id: "1000",
      projectId: 1,
      code: "f230fh0g3",
      name: "Bamboo Watch",
      description: "Product Description",
      price: 65,
      category: "Accessories",
      quantity: 24,
      inventoryStatus: "INSTOCK",
    },
    {
      id: "1001",
      projectId: 1,
      code: "nvklal433",
      name: "Black Watch",
      description: "Product Description",
      price: 72,
      category: "Accessories",
      quantity: 61,
      inventoryStatus: "INSTOCK",
    },
    {
      id: "1002",
      projectId: 2,
      code: "zz21cz3c1",
      name: "Blue Band",
      description: "Product Description",
      price: 79,
      category: "Fitness",
      quantity: 2,
      inventoryStatus: "LOWSTOCK",
    },
    {
      id: "1003",
      projectId: 3,
      code: "244wgerg2",
      name: "Blue T-Shirt",
      description: "Product Description",
      price: 29,
      category: "Clothing",
      quantity: 25,
      inventoryStatus: "INSTOCK",
    },
    {
      id: "1004",
      projectId: 5,
      code: "h456wer53",
      name: "Bracelet",
      description: "Product Description",
      price: 15,
      category: "Accessories",
      quantity: 73,
      inventoryStatus: "INSTOCK",
    },
  ],
};
