export const Data = {
  data: [
    {
      id: "1000",
      projectId: 1,
      code: "f230fh0g3",
      name: "Jorge Pérez",
      description: "Product Description",
      price: 65,
      category: "Accessories",
      quantity: 24,
      creationDate: "27/9/2022",
    },
    {
      id: "1001",
      projectId: 1,
      code: "nvklal433",
      name: "Andy García",
      description: "Product Description",
      price: 72,
      category: "Accessories",
      quantity: 61,
      creationDate: "27/9/2022",
    },
    {
      id: "1002",
      projectId: 2,
      code: "zz21cz3c1",
      name: "Pepe Fdez",
      description: "Product Description",
      price: 79,
      category: "Fitness",
      quantity: 2,
      creationDate: "27/9/2022",
    },
    {
      id: "1003",
      projectId: 3,
      code: "244wgerg2",
      name: "Federico Lorca",
      description: "Product Description",
      price: 29,
      category: "Clothing",
      quantity: 25,
      creationDate: "27/9/2022",
    },
    {
      id: "1004",
      projectId: 5,
      code: "h456wer53",
      name: "Julio Pulido",
      description: "este producto es una kk",
      price: 15,
      category: "Accessories",
      quantity: 73,
      creationDate: "27/9/2022",
    },
  ],
};
